### ISSUE TITLE
"python: error while loading shared libraries: libpython3.3m.so.1.0: cannot open shared object file: No such file or directory :" Error after creating openshift cartridge

### ISSUE THREAD

**Issue by shrinath-shenoy** [gsterjov/openshift-advanced-python-cartridge#1]
After creating the cartridge from this repo python 2 and python both are throwing their respective library not found error after creating the openshift cartrige. Cannot log into python scripting shell.

**Comment by grafuls** [comment]
you can access the python shell with absolute path:
[myapp]> /usr/bin/python
Python 2.6.6 (r266:84292, May 22 2015, 08:34:51) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

**Comment by izderadicka** [comment]
This will not help very much because it's different version of python then one used in virtenv

this is missing in environment 

```
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rh/python27/root/usr/lib64
```

**Comment by deargle** [comment]
I'm trying to figure out why adding 

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rh/python27/root/usr/lib64
```

to my `.bash_profile` isn't sticking. I have to re-source my `.bash_profile` after ssh'ing in. Other things in my `.bash_profile` are working.

**Comment by deargle** [comment]
Putting this in `.bash_profile` works:

```
scl enable python27 bash
```

It's not the same python binary as is in the virtualenv but it has its installed pip packages.

**Comment by deargle** [comment]
Figured it out, see PR #4
